name: money_tracker_get_cli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  animated_text_kit: ^4.2.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.5.3+1
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^0.6.0
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^2.3.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  lottie: ^1.3.0
  package_info_plus: ^1.4.2
  pie_chart: ^5.1.0
  restart_app: ^1.1.0
  rxdart: ^0.27.3
  timezone: ^0.8.0
  top_snackbar_flutter: ^2.0.0

dev_dependencies: 
  build_runner: ^2.1.10
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.2

flutter: 
  uses-material-design: true
  assets:
    - assets/images/MoneyManager.png
    - assets/animations/85023-no-data.json
    - assets/animations/99281-beezpay-loading-animation.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
    - family: ZenDots
      fonts:
        - asset: assets/fonts/ZenDots-Regular.ttf
    - family: Releway
      fonts:
        - asset: assets\fonts\Raleway-VariableFont_wght.ttf
